site_name: A Technical Writer's Tech Blog 

nav:
  - 블로거 소개: 'index.md'
  - 개발 프로젝트:
    - 문서 엔지니어링(Wordpress/HTML):
      - 깨진 링크 찾기: 'blc.md'
      - 국문 콘텐츠에서 영단어 추출하기: 'eng-word-extract.md'
      - 특정 영단어만 인라인 포맷팅하기: 'format-eng-word.md'
    - 실생활 도구:
      - 축의금 정산 도우미: 'wedding.md'

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    primary: "black"
    accent: "blue"

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/khy86/
    # - icon: fontawesome/brands/github
    #   link: https://github.com/SkyDominator

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      auto_title: true
      anchor_linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.snippets:
      check_paths: true
      url_download: false
      url_max_size: 33554432
      url_timeout: 10
      # auto_append:
      #   - includes/abbreviations.md