site_name: A Technical Writer's Tech Blog 
site_description: "Technical Writing, Document Engineering, and Life Tools"
site_author: "Ray Kim"

nav:
  - Hello World: index.md
  - Technical Writing:
    - BitNet:
      - Install & Build: tw/bitnet-2025-04-25.md
  - Dev:
theme:
  name: material
  logo: "images/logo.png"
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    primary: "black"
    accent: "blue"

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/khy86/
    # - icon: fontawesome/brands/github
    #   link: https://github.com/SkyDominator

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      auto_title: true
      anchor_linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.snippets:
      check_paths: true
      url_download: false
      url_max_size: 33554432
      url_timeout: 10
      # auto_append:
      #   - includes/abbreviations.md